## Numpy

In [3]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# numpy as np

In [6]:
import numpy as np

arr  = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


# Numpy creating Arrays

In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
import numpy as np

arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


# 0-D Arrays

In [12]:
import numpy as np

arr = np.array(10)

print(arr)


10


# 1-D Arrays

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays

In [25]:
import numpy as np

arr = np.array([[1, 2, 3],[4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


# 3-D arrays


In [22]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]])

print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## number of dimensions

In [24]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays



In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


## Access Array Elements

In [28]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2])

3


## Access 2-D Arrays

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])